version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ********
      MYSQL_DATABASE: puppytalk
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    deploy:
      resources:
        limits:
          memory: 300M

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 100M

  puppytalk-api:
    image: puppytalk_puppytalk-api:latest
    container_name: puppytalk-api
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/puppytalk?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=****
      - SPRING_DATASOURCE_PASSWORD=********
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=10MB
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=50MB

      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379

      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
      - KAKAO_CLIENT_ID=
      - NAVER_CLIENT_ID=
      - NAVER_CLIENT_SECRET=

      - SPRING_CLOUD_AWS_CREDENTIALS_ACCESS_KEY=
      - SPRING_CLOUD_AWS_CREDENTIALS_SECRET_KEY=
      - SPRING_CLOUD_AWS_REGION_STATIC=
      - SPRING_CLOUD_AWS_S3_BUCKET=

      - JWT_SECRET_KEY=
      - IAMPORT_KEY=
      - IAMPORT_SECRET=
      - FILE_UPLOAD_DIR=
      - AI_SERVER_URL=
    deploy:
      resources:
        limits:
          memory: 500M
