name: Deploy to AWS

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/puppytalk-api:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/puppytalk-api:latest

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            cd ~/puppytalk
            
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/puppytalk-api:latest
            
            sudo docker tag ${{ secrets.DOCKER_USERNAME }}/puppytalk-api:latest puppytalk_puppytalk-api:latest
            
            sudo docker-compose up -d puppytalk-api
            
            sudo docker image prune -f